/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ['@xxx/eslint-rules'],
  rules: {
    '@xxx/eslint-rules/example-rule': 'error',
  },
};
