/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

import recommended from './configs/recommended';
import exampleRule from './rules/example-rule';

export = {
  configs: {
    recommended,
  },
  rules: {
    'example-rule': exampleRule,
  },
};
